// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMNHvgpGfoQ45_0N2HycKOC77h8pdD290',
    appId: '1:1061255638870:web:287ce426a97b4acbd6b0f7',
    messagingSenderId: '1061255638870',
    projectId: 'mentalhealth-app-demo',
    authDomain: 'mentalhealth-app-demo.firebaseapp.com',
    storageBucket: 'mentalhealth-app-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr_1ZF4TyXAOWyBJCtBvi6IXML5BylFRA',
    appId: '1:1061255638870:android:f2361091d7f2c2ffd6b0f7',
    messagingSenderId: '1061255638870',
    projectId: 'mentalhealth-app-demo',
    storageBucket: 'mentalhealth-app-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7RbyLv5TK-VqYSc3DjGwufdi0EfqYFfQ',
    appId: '1:1061255638870:ios:9483d15fa4c51c0bd6b0f7',
    messagingSenderId: '1061255638870',
    projectId: 'mentalhealth-app-demo',
    storageBucket: 'mentalhealth-app-demo.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7RbyLv5TK-VqYSc3DjGwufdi0EfqYFfQ',
    appId: '1:1061255638870:ios:b27f98bf5fa557ccd6b0f7',
    messagingSenderId: '1061255638870',
    projectId: 'mentalhealth-app-demo',
    storageBucket: 'mentalhealth-app-demo.firebasestorage.app',
    iosBundleId: 'com.example.mentalhealApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMNHvgpGfoQ45_0N2HycKOC77h8pdD290',
    appId: '1:1061255638870:web:54d756e5bb4698ded6b0f7',
    messagingSenderId: '1061255638870',
    projectId: 'mentalhealth-app-demo',
    authDomain: 'mentalhealth-app-demo.firebaseapp.com',
    storageBucket: 'mentalhealth-app-demo.firebasestorage.app',
  );

}